name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Checkout
      uses: actions/checkout@v4.1.5

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.11.1

    - name: Install dependencies
      run: npm install

    - name: Run eslint
      run: npx eslint src/**

    - name: Build
      run: npm run build:prod

    - name: Clear S3
      if: success()
      run: aws s3 rm s3://josephalcantara --exclude "*" --include "*.txt" --include "*.js" --include "*.ico" --include "*.html" --include "*.css"

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/portfolio-joseph/browser s3://josephalcantara --cache-control "max-age=0"
